@startuml
actor 用户
participant 宁夏好差评前端
participant 宁夏好差评后台
participant 国家好差评
participant 12345系统
== 评价提交阶段 ==
用户 -> 宁夏好差评后台: 提交评价数据
activate 宁夏好差评后台
宁夏好差评后台 -> 宁夏好差评后台: 保存评价数据
宁夏好差评后台 -> 国家好差评: 实时推送评价数据
activate 国家好差评
deactivate 国家好差评
== 评价审核阶段 ==
alt 好评
    opt 无文字评价
        宁夏好差评后台 -> 宁夏好差评前端: 文字内容审核
        activate 宁夏好差评前端
        宁夏好差评前端 --> 宁夏好差评后台: 返回审核结果
        deactivate 宁夏好差评前端
        宁夏好差评后台 -> 国家好差评: 上报文字内容审核结果，且为有效评价
        activate 国家好差评
        deactivate 国家好差评
    end
else 差评
    opt 有文字评价
        宁夏好差评后台 -> 宁夏好差评前端: 文字内容审核
        activate 宁夏好差评前端
        宁夏好差评前端 --> 宁夏好差评后台: 返回审核结果
        deactivate 宁夏好差评前端
        宁夏好差评后台 -> 国家好差评: 上报文字内容审核结果
        activate 国家好差评
        deactivate 国家好差评
    end
    宁夏好差评后台 -> 12345系统: 提交12345审核是否有效
    activate 12345系统
    宁夏好差评后台-> 12345系统: 查询审核结果
    12345系统 --> 宁夏好差评后台: 返回是否有效
    deactivate 12345系统
    alt 无效
        宁夏好差评后台 -> 国家好差评: 上报无效评价
        activate 国家好差评
        deactivate 国家好差评
== 评价整改阶段 ==
    else 有效
        宁夏好差评后台 -> 12345系统: 查询是否可以按期整改
        activate 12345系统
        12345系统 --> 宁夏好差评后台: 返回是否可以按期整改，若无法按期整改，提供相关信息
        deactivate 12345系统
        alt 可以按期整改
            宁夏好差评后台 -> 12345系统: 查询整改结果
            activate 12345系统
            12345系统 --> 宁夏好差评后台: 返回整改结果
            deactivate 12345系统
            宁夏好差评后台 -> 国家好差评: 上报评价有效，及其整改结果
            activate 国家好差评
            deactivate 国家好差评
        else 无法按期整改
            宁夏好差评后台 -> 国家好差评: 上报评价有效，延期整改相关信息
            activate 国家好差评
            deactivate 国家好差评
            宁夏好差评后台 -> 12345系统: 查询整改结果
            activate 12345系统
            12345系统 --> 宁夏好差评后台: 返回整改结果
            deactivate 12345系统
            宁夏好差评后台 -> 国家好差评: 上报整改结果
            activate 国家好差评
            deactivate 国家好差评
            deactivate 宁夏好差评后台
        end
    end
end
@enduml