#开发环境配置

#数据库配置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://10.128.128.43:13308/dasevdb?characterEncoding=utf8&&useSSL=true&serverTimezone=Asia/Shanghai
            username: app
            password: root123456
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
    database: 0 # 默认库
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0


img:
  path:
    qr: \Users\gaoyiping\Documents\Code\Img