# 本地环境配置

# 数据库配置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8&&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: 66666666
  # Redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

img:
  path:
    qr: \Users\gaoyiping\Documents\Code\Img
