server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据库配置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jsj?characterEncoding=utf8&&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: 66666666
  # Redis配置
  redis:
    host: localhost
    port: 6379
    #    sentinel:
    #      master: Dasevred
    #      nodes: 10.128.128.45:26375,10.128.128.46:26375,10.128.128.47:26375
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

img:
  path:
    qr: \Users\gaoyiping\Documents\Code\Img
